gitpod:
  # This field must be set to your domain name. Leaving it set to its default value will result in
  # a non-functional installation.
  hostname: idelms.pratian.com

  # If you have a static IP that your domain resolves to, set it here.
  # Leaving this field set to its default value is fine. Kubernetes will assign you an IP address
  # during deployment.
  components:
    proxy:
      loadBalancerIP: null

  # Gitpod needs at least one auth provider to allow users to log in.
  # The auth providers below are examples only. Please change/remove them to fit your installation.
  authProviders:
  - id: "Example Github"
    host: "github.com"
    protocol: "https"
    type: "GitHub"
    oauth:
      clientId: "b532a84c0c95c2e7bc2f"
      clientSecret: "12c0115488712e92d99041cd239a93c13925c817"
      callBackUrl: "http://idelms.pratian.com/auth/github/callback"
      settingsUrl: "https://github.com/settings/connections/applications/b532a84c0c95c2e7bc2f"

  # RBAC is enabled by default. If your cluster does not use RBAC, set this flag to false so that
  # we do not attempt to install PodSecurityPolicies and the likes.
  installPodSecurityPolicies: true
